export const SET_IS_AUTH = 'SET_IS_AUTHORIZATION'
export const SET_ROOM_ID = 'SET_ROOM_ID'
export const SET_USERS = 'SET_USERS'
export const SET_USER_NAME = 'SET_USER_NAME'
export const SET_NEW_MESSAGE = 'SET_NEW_MESSAGE'
export const SET_MESSAGES = 'SET_MESSAGES'